"""empty message

Revision ID: 7f2dcdbef5c9
Revises: 24bca95ea274
Create Date: 2024-04-11 11:22:37.332335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f2dcdbef5c9'
down_revision = '24bca95ea274'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_model', schema=None) as batch_op:
        batch_op.drop_constraint('Essai1', type_='unique')
        batch_op.drop_column('email')

        #batch_op.add_column(sa.Column('email', sa.String(), nullable=False))
        #batch_op.create_unique_constraint('Essai2', ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=256), nullable=False))
        batch_op.create_unique_constraint('Essai1', ['email'])

    # ### end Alembic commands ###
