"""empty message

Revision ID: 24bca95ea274
Revises: d9256c7f0036
Create Date: 2024-04-11 11:12:36.936064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24bca95ea274'
down_revision = 'd9256c7f0036'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=256), nullable=False))
        batch_op.create_unique_constraint('Essai1', ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_model', schema=None) as batch_op:
        batch_op.drop_constraint('Essai1', type_='unique')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
